name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'rs/**'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout Repository
        uses: actions/checkout@v4

      - name: âš™ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ”‘ Log in to GitHub Container Registry (ghcr.io)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ“ Set Environment Variables
        id: vars
        run: |
          # Get short SHA for tagging
          SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)
          echo "sha_short=$SHA_SHORT" >> $GITHUB_OUTPUT

          # Define the full image name
          IMAGE_NAME="ghcr.io/${{ github.repository }}/rust-app"
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: ğŸ—ï¸ Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./rs # The Docker build context is the /rs folder
          file: ./rs/Dockerfile # Assuming the Dockerfile is inside /rs
          push: true
          tags: |
            ${{ steps.vars.outputs.image_name }}:latest
            ${{ steps.vars.outputs.image_name }}:${{ steps.vars.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
